apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: xrplevm-node
spec:
  serviceName: xrplevm-node
  replicas: 1
  selector:
    matchLabels:
      app: xrplevm-node
  template:
    metadata:
      labels:
        app: xrplevm-node
    spec:
      containers:
      - name: xrplevm-node
        image: peersyst/exrp:latest
        imagePullPolicy: IfNotPresent
        command: ["exrpd", "start"]
        ports:
        - containerPort: 26656  # P2P
          name: p2p
        - containerPort: 26657  # RPC
          name: rpc
        - containerPort: 1317   # REST
          name: rest
        - containerPort: 8545   # EVM RPC
          name: evm
        env:
        - name: DAEMON_NAME
          value: "exrpd"
        - name: DAEMON_HOME
          value: "/root/.exrpd"
        resources:
          requests:
            cpu: "1"
            memory: "4Gi"
          limits:
            cpu: "2"
            memory: "8Gi"
        volumeMounts:
        - name: data
          mountPath: /root/.exrpd
        # livenessProbe: null
        # readinessProbe: null
      volumes:
      - name: data
        hostPath:
          path: /hosthome/.exrpd  # Minikube에 마운트된 경로
          type: Directory